; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.29917.0 

	TITLE	B:\003_¼ö¾÷»çÀü¼Ò½º¸ðÀ½\»çÀü¼Ò½º\2021_LGE_°í±Þ_CPP_1Â÷\DAY1\2_thiscall1.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?set@Point@@QAEXHH@Z				; Point::set
PUBLIC	?foo@Point@@SAXH@Z				; Point::foo
PUBLIC	_main
; Function compile flags: /Odtp
; File B:\003_¼ö¾÷»çÀü¼Ò½º¸ðÀ½\»çÀü¼Ò½º\2021_LGE_°í±Þ_CPP_1Â÷\DAY1\2_thiscall1.cpp
_TEXT	SEGMENT
_p2$ = -16						; size = 8
_p1$ = -8						; size = 8
_main	PROC

; 23   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H

; 24   : 	Point::foo(10); // push 10

	push	10					; 0000000aH
	call	?foo@Point@@SAXH@Z			; Point::foo
	add	esp, 4

; 25   : 					// call Point::foo
; 26   : 
; 27   : 	Point p1, p2;
; 28   : 
; 29   : 	p1.set(10, 20); // set( &p1, 10, 20 )

	push	20					; 00000014H
	push	10					; 0000000aH
	lea	ecx, DWORD PTR _p1$[ebp]
	call	?set@Point@@QAEXHH@Z			; Point::set

; 30   : 	p2.set(10, 20); // set( &p2, 10, 20 )

	push	20					; 00000014H
	push	10					; 0000000aH
	lea	ecx, DWORD PTR _p2$[ebp]
	call	?set@Point@@QAEXHH@Z			; Point::set

; 31   : 					// 32bit ì—ì„œëŠ”
; 32   : 					// push 20
; 33   : 					// push 10  ===> ì‹¤ì œ ì¸ìžëŠ” ìŠ¤íƒìœ¼ë¡œ
; 34   : 					// mov  ecx, &p2 ê°ì²´ëŠ” ë ˆì§€ìŠ¤í„°ì— ë‹´ì•„ì„œ
; 35   : 					//				 64bit ëŠ” rcx ë ˆì§€ìŠ¤í„°
; 36   : 					// call Point::set
; 37   : 
; 38   : 	// g++ 2_thiscall1.cpp  -S    => ì†ŒìŠ¤.s  
; 39   : 	// cl  2_thiscall1.cpp  /FAs  => ì†ŒìŠ¤.asm
; 40   : }

	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File B:\003_¼ö¾÷»çÀü¼Ò½º¸ðÀ½\»çÀü¼Ò½º\2021_LGE_°í±Þ_CPP_1Â÷\DAY1\2_thiscall1.cpp
;	COMDAT ?foo@Point@@SAXH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
?foo@Point@@SAXH@Z PROC					; Point::foo, COMDAT

; 16   : 	{

	push	ebp
	mov	ebp, esp

; 17   : //		x = a;				// this->x = aë¡œ ë³€ê²½í•´ì•¼ í•˜ëŠ”ë°...
; 18   : 							// ë¬¸ì œëŠ” thisê°€ ì—†ë‹¤!!
; 19   : 						// ê·¸ëž˜ì„œ static ë©¤ë²„ í•¨ìˆ˜ì—ì„œëŠ” ë©¤ë²„ ë°ì´íƒ€ ì ‘ê·¼ ì•ˆë¨
; 20   : 	}

	pop	ebp
	ret	0
?foo@Point@@SAXH@Z ENDP					; Point::foo
_TEXT	ENDS
; Function compile flags: /Odtp
; File B:\003_¼ö¾÷»çÀü¼Ò½º¸ðÀ½\»çÀü¼Ò½º\2021_LGE_°í±Þ_CPP_1Â÷\DAY1\2_thiscall1.cpp
;	COMDAT ?set@Point@@QAEXHH@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?set@Point@@QAEXHH@Z PROC				; Point::set, COMDAT
; _this$ = ecx

; 11   : 	{						

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 12   : 		x = a;			   // this->x = a	 

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _a$[ebp]
	mov	DWORD PTR [eax], ecx

; 13   : 		y = b;			   // this->y = b

	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR _b$[ebp]
	mov	DWORD PTR [edx+4], eax

; 14   : 	}		

	mov	esp, ebp
	pop	ebp
	ret	8
?set@Point@@QAEXHH@Z ENDP				; Point::set
_TEXT	ENDS
END
