all:
	g++ -std=c++17 7_reference_counting2.cpp
	./a.out


kkk:
	g++ -std=c++17 1_상수멤버함수.cpp
	g++ -std=c++17 1_상수멤버함수2.cpp
	g++ -std=c++17 2_thiscall1.cpp
	g++ -std=c++17 2_thiscall2.cpp
	g++ -std=c++17 2_thiscall3.cpp
	g++ -std=c++17 2_thiscall4.cpp
	g++ -std=c++17 2_thiscall5.cpp
	g++ -std=c++17 2_thiscall6.cpp
	g++ -std=c++17 2_thiscall7.cpp
	g++ -std=c++17 3_constructor1.cpp
	g++ -std=c++17 3_constructor2.cpp
	g++ -std=c++17 3_constructor3.cpp
	g++ -std=c++17 3_constructor4.cpp
	g++ -std=c++17 4_trivial1.cpp
	g++ -std=c++17 4_trivial2.cpp
	g++ -std=c++17 4_trivial3.cpp
	g++ -std=c++17 4_trivial4.cpp
	g++ -std=c++17 4_trivial5.cpp
	g++ -std=c++17 4_trivial6.cpp
	g++ -std=c++17 6_conversion1.cpp
	g++ -std=c++17 6_conversion2.cpp
	g++ -std=c++17 6_conversion3.cpp
	g++ -std=c++17 6_conversion4.cpp
	g++ -std=c++17 6_conversion5.cpp
	g++ -std=c++17 6_conversion6.cpp
	g++ -std=c++17 7_reference_counting1.cpp
	g++ -std=c++17 7_reference_counting2.cpp
