; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.29917.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?set@Point@@QEAAXHH@Z				; Point::set
PUBLIC	main
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+32
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	06204H
xdata	ENDS
; Function compile flags: /Odtp
; File B:\003_수업사전소스모음\사전소스\2021_LGE_고급_CPP_1차\DAY1\2_thiscall1.cpp
_TEXT	SEGMENT
p1$ = 32
main	PROC

; 15   : {

$LN3:
	sub	rsp, 56					; 00000038H

; 16   : 	Point p1, p2;
; 17   : 
; 18   : 	p1.set(10, 20); 

	mov	r8d, 20
	mov	edx, 10
	lea	rcx, QWORD PTR p1$[rsp]
	call	?set@Point@@QEAAXHH@Z			; Point::set

; 19   : }

	xor	eax, eax
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File B:\003_수업사전소스모음\사전소스\2021_LGE_고급_CPP_1차\DAY1\2_thiscall1.cpp
;	COMDAT ?set@Point@@QEAAXHH@Z
_TEXT	SEGMENT
this$ = 8
a$ = 16
b$ = 24
?set@Point@@QEAAXHH@Z PROC				; Point::set, COMDAT

; 8    : 	{						

	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx

; 9    : 		x = a;				

	mov	rax, QWORD PTR this$[rsp]
	mov	ecx, DWORD PTR a$[rsp]
	mov	DWORD PTR [rax], ecx

; 10   : 		y = b;				

	mov	rax, QWORD PTR this$[rsp]
	mov	ecx, DWORD PTR b$[rsp]
	mov	DWORD PTR [rax+4], ecx

; 11   : 	}						

	ret	0
?set@Point@@QEAAXHH@Z ENDP				; Point::set
_TEXT	ENDS
END
