1_new1:
	g++ -std=c++11 1_new1.cpp -o a
	./a
1_new3:
	g++ -std=c++11 1_new3.cpp -o a
	./a
1_new4:
	g++ -std=c++11 1_new4.cpp -o a
	./a
2_traits2:
	g++ -std=c++11 2_traits2.cpp -o a
	./a
partially_specialization:
	g++ -std=c++11 partially_specialization.cpp -o a
	./a
2_traits3:
	g++ -std=c++11 2_traits3.cpp -o a
	./a
2_traits4:
	g++ -std=c++11 2_traits4.cpp -o a
	./a
3_int2type1:
	g++ -std=c++11 3_int2type1.cpp -o a
	./a
3_int2type2:
	g++ -std=c++11 3_int2type2.cpp -o a
	./a
3_int2type3:
	g++ -std=c++11 3_int2type3.cpp -o a
	./a
3_int2type4:
	g++ -std=c++11 3_int2type4.cpp -o a
	./a
3_int2type6:
	g++ -std=c++11 3_int2type6.cpp -o a
	./a
3_int2type8:
	g++ -std=c++17 3_int2type8.cpp -o a
	./a
4_typename:
	g++ -std=c++11 4_typename.cpp -o a
	./a
5_notMeasuredExpr:
	g++ -std=c++11 5_notMeasuredExpr.cpp -o a
	./a
6_SFINAE1:
	g++ -std=c++11 6_SFINAE1.cpp -o a
	./a
6_SFINAE2:
	g++ -std=c++11 6_SFINAE2.cpp -o a
	./a
6_SFINAE3:
	g++ -std=c++11 6_SFINAE3.cpp -o a
	./a
7_enableif1:
	g++ -std=c++11 7_enableif1.cpp -o a
	./a
7_enableif2:
	g++ -std=c++11 7_enableif2.cpp -o a
	./a
7_enableif3:
	g++ -std=c++11 7_enableif3.cpp -o a
	./a
9_printv1:
	g++ -std=c++11 9_printv1.cpp -o a
	./a
9_printv3:
	g++ -std=c++17 9_printv3.cpp -o a
	./a
10_trivial1:
	g++ -std=c++11 10_trivial1.cpp -o a
	./a
10_trivial2:
	g++ -std=c++17 10_trivial2.cpp -o a
	./a
10_trivial3:
	g++ -std=c++17 10_trivial3.cpp -o a
	./a
10_trivial4:
	g++ -std=c++11 10_trivial4.cpp -o a
	./a
11_is_abstract1:
	g++ -std=c++11 11_is_abstract1.cpp -o a
	./a
11_is_abstract2:
	g++ -std=c++11 11_is_abstract2.cpp -o a
	./a
11_is_abstract3:
	g++ -std=c++17 11_is_abstract3.cpp -o a
	./a
11_is_abstract4:
	g++ -std=c++17 11_is_abstract4.cpp -o a
	./a
12_member_detect2:
	g++ -std=c++17 12_member_detect2.cpp -o a
	./a
12_member_detect3:
	g++ -std=c++17 12_member_detect3.cpp -o a
	./a
12_member_detect4:
	g++ -std=c++17 12_member_detect4.cpp -o a
	./a
12_member_detect5:
	g++ -std=c++17 12_member_detect5.cpp -o a
	./a
12_member_detect6:
	g++ -std=c++17 12_member_detect6.cpp -o a
	./a
memfun4:
	g++ -std=c++17 memfun4.cpp -o a
	./a
1_member_pointer:
	g++ -std=c++17 1_member_pointer.cpp -o a
	./a
2_smart_pointer1:
	g++ -std=c++17 2_smart_pointer1.cpp -o a
	./a
1_member_pointer4:
	g++ -std=c++17 1_member_pointer4.cpp -o a
	./a
1_member_pointer5:
	g++ -std=c++17 1_member_pointer5.cpp -o a
	./a
1_member_pointer7:
	g++ -std=c++11 1_member_pointer7.cpp -o a
	./a
1_member_pointer8:
	g++ -std=c++11 1_member_pointer8.cpp -o a
	./a
2_smart_pointer2:
	g++ -std=c++17 2_smart_pointer2.cpp -o a
	./a
2_smart_pointer4:
	g++ -std=c++17 2_smart_pointer4.cpp -o a
	./a
3_forwarding_reference2:
	g++ -std=c++17 3_forwarding_reference2.cpp -o a
	./a
3_forwarding_reference4:
	g++ -std=c++11 3_forwarding_reference4.cpp -o a
	./a
3_forwarding_reference5:
	g++ -std=c++11 3_forwarding_reference5.cpp -o a
	./a
3_forwarding_reference6:
	g++ -std=c++11 3_forwarding_reference6.cpp -o a
	./a
3_forwarding_reference7:
	g++ -std=c++11 3_forwarding_reference7.cpp -o a
	./a
3_forwarding_reference8:
	g++ -std=c++11 3_forwarding_reference8.cpp -o a
	./a
3_forwarding_reference10:
	g++ -std=c++11 3_forwarding_reference10.cpp -o a
	./a
3_forwarding_reference11:
	g++ -std=c++11 3_forwarding_reference11.cpp -o a
	./a
reference:
	g++ -std=c++11 reference.cpp -o a
	./a
reference2:
	g++ -std=c++11 reference2.cpp -o a
	./a
3_forwarding_reference12:
	g++ -std=c++11 3_forwarding_reference12.cpp -o a
	./a
4_temporary1:
	g++ -std=c++11 4_temporary1.cpp -o a
	./a
4_temporary2:
	g++ -std=c++11 4_temporary2.cpp -o a
	./a
4_temporary3:
	g++ -std=c++11 4_temporary3.cpp -o a
	./a
4_temporary5:
	g++ -std=c++11 4_temporary5.cpp -o a
	./a
4_temporary6:
	g++ -std=c++11 4_temporary6.cpp -o a -fno-elide-constructors
	./a
1_EMPTY1:
	g++ -std=c++11 1_EMPTY1.cpp -o a -fno-elide-constructors
	./a
1_EMPTY2:
	g++ -std=c++11 1_EMPTY2.cpp -o a -fno-elide-constructors
	./a
1_EMPTY3:
	g++ -std=c++11 1_EMPTY3.cpp -o a -fno-elide-constructors
	./a
1_EMPTY4:
	g++ -std=c++11 1_EMPTY4.cpp -o a -fno-elide-constructors
	./a
1_EMPTY5:
	g++ -std=c++11 1_EMPTY5.cpp -o a -fno-elide-constructors
	./a
1_EMPTY6:
	g++ -std=c++11 1_EMPTY6.cpp -o a -fno-elide-constructors
	./a
1_EMPTY7:
	g++ -std=c++11 1_EMPTY7.cpp -o a -fno-elide-constructors
	./a
concept1:
	g++ -fconcepts -std=c++17 concept1.cpp -o a -fno-elide-constructors
	./a
2_EBCO:
	g++ -std=c++11 2_EBCO.cpp -o a -fno-elide-constructors
	./a
2_EBCO2:
	g++ -std=c++11 2_EBCO2.cpp -o a -fno-elide-constructors
	./a
2_EBCO3:
	g++ -std=c++11 2_EBCO3.cpp -o a -fno-elide-constructors
	./a
3_function_object1:
	g++ -std=c++11 3_function_object1.cpp -o a -fno-elide-constructors
	./a
3_function_object2:
	g++ -std=c++11 3_function_object2.cpp -o a -fno-elide-constructors
	./a
3_function_object3:
	#g++ -std=c++11 3_function_object3.cpp  -S -g -fverbose-asm
	as -alhnd 3_function_object3.s > 3_function_object3.list
	g++ -g -O -Wa,-aslh 3_function_object3.cpp > 3_function_object3.txt
	g++ -std=c++11 3_function_object3.cpp -o a
	./a
3_function_object4:
	g++ -std=c++11 3_function_object4.cpp -o a
	./a
4_unique_ptr1:
	g++ -std=c++11 4_unique_ptr1.cpp -o a
	./a
4_unique_ptr2:
	g++ -std=c++11 4_unique_ptr2.cpp -o a
	./a
4_unique_ptr3:
	g++ -std=c++11 4_unique_ptr3.cpp -o a
	./a
4_unique_ptr4:
	g++ -std=c++11 4_unique_ptr4.cpp -o a
	./a
4_unique_ptr5:
	g++ -std=c++11 4_unique_ptr5.cpp -o a
	./a
4_unique_ptr6:
	g++ -std=c++11 4_unique_ptr6.cpp -o a
	./a
4_unique_ptr7:
	g++ -std=c++11 4_unique_ptr7.cpp -o a
	./a
4_unique_ptr8:
	g++ -std=c++17 4_unique_ptr8.cpp -o a
	./a
tuple_size:
	g++ -std=c++11 tuple_size.cpp -o a
	./a
5_move1:
	g++ -std=c++11 5_move1.cpp -o a
	./a
5_move2:
	g++ -std=c++11 5_move2.cpp -o a
	./a
5_move3:
	g++ -std=c++11 5_move3.cpp -o a
	./a
5_move4:
	g++ -std=c++11 5_move4.cpp -o a
	./a
5_move5:
	g++ -std=c++11 5_move5.cpp -o a
	./a
5_move6:
	g++ -std=c++11 5_move6.cpp -o a
	./a
5_move7:
	g++ -std=c++11 5_move7.cpp -o a
	./a
5_move8:
	g++ -std=c++11 5_move8.cpp -o a
	./a
5_move9:
	g++ -std=c++11 5_move9.cpp -o a
	./a
5_move10:
	g++ -std=c++11 5_move10.cpp -o a
	./a
5_move11:
	g++ -std=c++11 5_move11.cpp -o a
	./a
5_move12:
	g++ -std=c++11 5_move12.cpp -o a
	./a
5_move13:
	g++ -std=c++11 5_move13.cpp -o a
	./a
6_unique_ptr9:
	g++ -std=c++11 6_unique_ptr9.cpp -o a
	./a
6_unique_ptr10:
	g++ -std=c++11 6_unique_ptr10.cpp -o a
	./a
6_unique_ptr11:
	g++ -std=c++11 6_unique_ptr11.cpp -o a
	./a
1_checked_delete:
	g++ -std=c++11 1_checked_delete.cpp -o a
	./a
2_explicit:
	g++ -std=c++11 2_explicit.cpp -o a
	./a
2_explicit2:
	g++ -std=c++11 2_explicit2.cpp -o a
	./a
2_explicit3:
	g++ -std=c++11 2_explicit3.cpp -o a
	./a
2_explicit4:
	g++ -std=c++11 2_explicit4.cpp -o a
	./a
3_make:
	g++ -std=c++11 3_make.cpp -o a
	./a
3_make2:
	g++ -std=c++17 3_make2.cpp -o a
	./a
4_coercion:
	# need compile check
	g++ -std=c++11 4_coercion.cpp -o a
	./a
4_coercion2:
	# need compile check
	g++ -std=c++11 4_coercion2.cpp -o a
	./a
4_coercion3:
	# need compile check
	g++ -std=c++11 4_coercion3.cpp -o a
	./a
5_using:
	# need compile check
	g++ -std=c++11 5_using.cpp -o a
	./a
5_using2:
	# need compile check
	g++ -std=c++11 5_using2.cpp -o a
	./a
6_bind:
	g++ -std=c++11 6_bind.cpp -o a
	./a
6_bind2:
	g++ -std=c++11 6_bind2.cpp -o a
	./a
6_bind3:
	g++ -std=c++11 6_bind3.cpp -o a
	./a
6_bind4:
	g++ -std=c++11 6_bind4.cpp -o a
	./a
7_reference_wrapper:
	g++ -std=c++11 7_reference_wrapper.cpp -o a
	./a
7_reference_wrapper2:
	g++ -std=c++11 7_reference_wrapper2.cpp -o a
	./a
7_reference_wrapper3:
	# need compile check
	g++ -std=c++11 7_reference_wrapper3.cpp -o a
	./a
7_reference_wrapper4:
	g++ -std=c++11 7_reference_wrapper4.cpp -o a
	./a
8_policy:
	g++ -std=c++11 8_policy.cpp -o a
	./a
8_policy3:
	g++ -std=c++11 8_policy3.cpp -o a
	./a
8_policy4:
	g++ -std=c++11 8_policy4.cpp -o a
	./a
reference:
	g++ -std=c++11 reference.cpp -o a
	./a
8_policy5:
	g++ -std=c++11 8_policy5.cpp -o a
	./a
8_policy6:
	g++ -std=c++11 8_policy6.cpp -o a
	./a
all: 8_policy6
