1_new1:
	g++ -std=c++11 1_new1.cpp -o a
	./a
1_new3:
	g++ -std=c++11 1_new3.cpp -o a
	./a
1_new4:
	g++ -std=c++11 1_new4.cpp -o a
	./a
2_traits2:
	g++ -std=c++11 2_traits2.cpp -o a
	./a
partially_specialization:
	g++ -std=c++11 partially_specialization.cpp -o a
	./a
2_traits3:
	g++ -std=c++11 2_traits3.cpp -o a
	./a
2_traits4:
	g++ -std=c++11 2_traits4.cpp -o a
	./a
3_int2type1:
	g++ -std=c++11 3_int2type1.cpp -o a
	./a
3_int2type2:
	g++ -std=c++11 3_int2type2.cpp -o a
	./a
3_int2type3:
	g++ -std=c++11 3_int2type3.cpp -o a
	./a
3_int2type4:
	g++ -std=c++11 3_int2type4.cpp -o a
	./a
3_int2type6:
	g++ -std=c++11 3_int2type6.cpp -o a
	./a
3_int2type8:
	g++ -std=c++17 3_int2type8.cpp -o a
	./a
all: 3_int2type8
