1_new1:
	g++ -std=c++11 1_new1.cpp -o a
	./a
1_new3:
	g++ -std=c++11 1_new3.cpp -o a
	./a
1_new4:
	g++ -std=c++11 1_new4.cpp -o a
	./a
2_traits2:
	g++ -std=c++11 2_traits2.cpp -o a
	./a
partially_specialization:
	g++ -std=c++11 partially_specialization.cpp -o a
	./a
2_traits3:
	g++ -std=c++11 2_traits3.cpp -o a
	./a
2_traits4:
	g++ -std=c++11 2_traits4.cpp -o a
	./a
3_int2type1:
	g++ -std=c++11 3_int2type1.cpp -o a
	./a
3_int2type2:
	g++ -std=c++11 3_int2type2.cpp -o a
	./a
3_int2type3:
	g++ -std=c++11 3_int2type3.cpp -o a
	./a
3_int2type4:
	g++ -std=c++11 3_int2type4.cpp -o a
	./a
3_int2type6:
	g++ -std=c++11 3_int2type6.cpp -o a
	./a
3_int2type8:
	g++ -std=c++17 3_int2type8.cpp -o a
	./a
4_typename:
	g++ -std=c++11 4_typename.cpp -o a
	./a
5_notMeasuredExpr:
	g++ -std=c++11 5_notMeasuredExpr.cpp -o a
	./a
6_SFINAE1:
	g++ -std=c++11 6_SFINAE1.cpp -o a
	./a
6_SFINAE2:
	g++ -std=c++11 6_SFINAE2.cpp -o a
	./a
6_SFINAE3:
	g++ -std=c++11 6_SFINAE3.cpp -o a
	./a
7_enableif1:
	g++ -std=c++11 7_enableif1.cpp -o a
	./a
7_enableif2:
	g++ -std=c++11 7_enableif2.cpp -o a
	./a
7_enableif3:
	g++ -std=c++11 7_enableif3.cpp -o a
	./a
9_printv1:
	g++ -std=c++11 9_printv1.cpp -o a
	./a
9_printv3:
	g++ -std=c++17 9_printv3.cpp -o a
	./a
10_trivial1:
	g++ -std=c++11 10_trivial1.cpp -o a
	./a
10_trivial2:
	g++ -std=c++17 10_trivial2.cpp -o a
	./a
10_trivial3:
	g++ -std=c++17 10_trivial3.cpp -o a
	./a
p: 10_trivial2
all: 10_trivial3
